apiVersion: apps/v1
kind: Deployment
metadata:
  name: asl-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asl
  template:
    metadata:
      labels:
        app: asl
    spec:
      containers:
        - name: api
          image: asl-service:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef: {name: asl-config}
            - secretRef: {name: asl-secrets}
          startupProbe:
            httpGet: {path: /health, port: 8000}
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet: {path: /health, port: 8000}
            periodSeconds: 10
          readinessProbe:
            httpGet: {path: /ready, port: 8000}
            periodSeconds: 5
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits: {cpu: "1", memory: 512Mi}